// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yatwxdpdlgwuwhjhuxli.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlhdHd4ZHBkbGd3dXdoamh1eGxpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNzUwOTIsImV4cCI6MjA2OTg1MTA5Mn0.1_7Wn4BFx8On42iTBfNzgDGCzDWYUtP2ogY70MEmGXk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});